'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace InvoiCyRecepcao
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InvoiCy", [Namespace]:="InvoiCy"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InvoiCy
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CabecalhoField As InvoiCyRecepcao.InvoiCyRecepcaoCabecalho
        
        Private InformacoesField As InvoiCyRecepcao.InvoiCyRecepcaoInformacoes
        
        Private DadosField As InvoiCyRecepcao.InvoiCy.DadosType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Cabecalho() As InvoiCyRecepcao.InvoiCyRecepcaoCabecalho
            Get
                Return Me.CabecalhoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CabecalhoField, value) <> true) Then
                    Me.CabecalhoField = value
                    Me.RaisePropertyChanged("Cabecalho")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Informacoes() As InvoiCyRecepcao.InvoiCyRecepcaoInformacoes
            Get
                Return Me.InformacoesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InformacoesField, value) <> true) Then
                    Me.InformacoesField = value
                    Me.RaisePropertyChanged("Informacoes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=2)>  _
        Public Property Dados() As InvoiCyRecepcao.InvoiCy.DadosType
            Get
                Return Me.DadosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DadosField, value) <> true) Then
                    Me.DadosField = value
                    Me.RaisePropertyChanged("Dados")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.CollectionDataContractAttribute(Name:="InvoiCy.DadosType", [Namespace]:="InvoiCy", ItemName:="DadosItem"),  _
         System.SerializableAttribute()>  _
        Public Class DadosType
            Inherits System.Collections.Generic.List(Of InvoiCyRecepcao.InvoiCyRecepcaoDadosItem)
        End Class
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InvoiCyRecepcao.Cabecalho", [Namespace]:="InvoiCy"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InvoiCyRecepcaoCabecalho
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private EmpPKField As String
        
        Private EmpCKField As String
        
        Private EmpCOField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property EmpPK() As String
            Get
                Return Me.EmpPKField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpPKField, value) <> true) Then
                    Me.EmpPKField = value
                    Me.RaisePropertyChanged("EmpPK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=1)>  _
        Public Property EmpCK() As String
            Get
                Return Me.EmpCKField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpCKField, value) <> true) Then
                    Me.EmpCKField = value
                    Me.RaisePropertyChanged("EmpCK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=2)>  _
        Public Property EmpCO() As String
            Get
                Return Me.EmpCOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpCOField, value) <> true) Then
                    Me.EmpCOField = value
                    Me.RaisePropertyChanged("EmpCO")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InvoiCyRecepcao.Informacoes", [Namespace]:="InvoiCy"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InvoiCyRecepcaoInformacoes
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private TextoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Texto() As String
            Get
                Return Me.TextoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextoField, value) <> true) Then
                    Me.TextoField = value
                    Me.RaisePropertyChanged("Texto")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InvoiCyRecepcao.DadosItem", [Namespace]:="InvoiCy"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InvoiCyRecepcaoDadosItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private DocumentoField As String
        
        Private ParametrosField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Documento() As String
            Get
                Return Me.DocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentoField, value) <> true) Then
                    Me.DocumentoField = value
                    Me.RaisePropertyChanged("Documento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Parametros() As String
            Get
                Return Me.ParametrosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ParametrosField, value) <> true) Then
                    Me.ParametrosField = value
                    Me.RaisePropertyChanged("Parametros")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Invoicyretorno", [Namespace]:="InvoiCy"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Invoicyretorno
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private MensagemField As InvoiCyRecepcao.Invoicyretorno.MensagemType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Mensagem() As InvoiCyRecepcao.Invoicyretorno.MensagemType
            Get
                Return Me.MensagemField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensagemField, value) <> true) Then
                    Me.MensagemField = value
                    Me.RaisePropertyChanged("Mensagem")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.CollectionDataContractAttribute(Name:="Invoicyretorno.MensagemType", [Namespace]:="InvoiCy", ItemName:="MensagemItem"),  _
         System.SerializableAttribute()>  _
        Public Class MensagemType
            Inherits System.Collections.Generic.List(Of InvoiCyRecepcao.InvoiCyRetornoMensagemItem)
        End Class
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InvoiCyRetorno.MensagemItem", [Namespace]:="InvoiCy"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InvoiCyRetornoMensagemItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodigoField As Integer
        
        Private DescricaoField As String
        
        Private DocumentosField As InvoiCyRecepcao.InvoiCyRetornoMensagemItem.DocumentosType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Codigo() As Integer
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Me.CodigoField.Equals(value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Descricao() As String
            Get
                Return Me.DescricaoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescricaoField, value) <> true) Then
                    Me.DescricaoField = value
                    Me.RaisePropertyChanged("Descricao")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Documentos() As InvoiCyRecepcao.InvoiCyRetornoMensagemItem.DocumentosType
            Get
                Return Me.DocumentosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentosField, value) <> true) Then
                    Me.DocumentosField = value
                    Me.RaisePropertyChanged("Documentos")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.CollectionDataContractAttribute(Name:="InvoiCyRetorno.MensagemItem.DocumentosType", [Namespace]:="InvoiCy", ItemName:="DocumentosItem"),  _
         System.SerializableAttribute()>  _
        Public Class DocumentosType
            Inherits System.Collections.Generic.List(Of InvoiCyRecepcao.InvoiCyRetornoMensagemItem.DocumentosItem)
        End Class
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="InvoiCyRetorno.MensagemItem.DocumentosItem", [Namespace]:="InvoiCy"),  _
         System.SerializableAttribute()>  _
        Partial Public Class DocumentosItem
            Inherits Object
            Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
            
            <System.NonSerializedAttribute()>  _
            Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
            
            Private DocumentoField As String
            
            Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
                Get
                    Return Me.extensionDataField
                End Get
                Set
                    Me.extensionDataField = value
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
            Public Property Documento() As String
                Get
                    Return Me.DocumentoField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.DocumentoField, value) <> true) Then
                        Me.DocumentoField = value
                        Me.RaisePropertyChanged("Documento")
                    End If
                End Set
            End Property
            
            Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
            
            Protected Sub RaisePropertyChanged(ByVal propertyName As String)
                Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
                If (Not (propertyChanged) Is Nothing) Then
                    propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
                End If
            End Sub
        End Class
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="InvoiCy", ConfigurationName:="InvoiCyRecepcao.recepcaoSoapPort")>  _
    Public Interface recepcaoSoapPort
        
        'CODEGEN: Generating message contract since the wrapper name (recepcao.Execute) of message ExecuteRequest does not match the default value (Execute)
        <System.ServiceModel.OperationContractAttribute(Action:="InvoiCyaction/ARECEPCAO.Execute", ReplyAction:="*")>  _
        Function Execute(ByVal request As InvoiCyRecepcao.ExecuteRequest) As InvoiCyRecepcao.ExecuteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="InvoiCyaction/ARECEPCAO.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As InvoiCyRecepcao.ExecuteRequest) As System.Threading.Tasks.Task(Of InvoiCyRecepcao.ExecuteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="recepcao.Execute", WrapperNamespace:="InvoiCy", IsWrapped:=true)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="InvoiCy", Order:=0)>  _
        Public Invoicyrecepcao As InvoiCyRecepcao.InvoiCy
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Invoicyrecepcao As InvoiCyRecepcao.InvoiCy)
            MyBase.New
            Me.Invoicyrecepcao = Invoicyrecepcao
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="recepcao.ExecuteResponse", WrapperNamespace:="InvoiCy", IsWrapped:=true)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="InvoiCy", Order:=0)>  _
        Public Invoicyretorno As InvoiCyRecepcao.Invoicyretorno
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Invoicyretorno As InvoiCyRecepcao.Invoicyretorno)
            MyBase.New
            Me.Invoicyretorno = Invoicyretorno
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface recepcaoSoapPortChannel
        Inherits InvoiCyRecepcao.recepcaoSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class recepcaoSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of InvoiCyRecepcao.recepcaoSoapPort)
        Implements InvoiCyRecepcao.recepcaoSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InvoiCyRecepcao_recepcaoSoapPort_Execute(ByVal request As InvoiCyRecepcao.ExecuteRequest) As InvoiCyRecepcao.ExecuteResponse Implements InvoiCyRecepcao.recepcaoSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute(ByVal Invoicyrecepcao As InvoiCyRecepcao.InvoiCy) As InvoiCyRecepcao.Invoicyretorno
            Dim inValue As InvoiCyRecepcao.ExecuteRequest = New InvoiCyRecepcao.ExecuteRequest()
            inValue.Invoicyrecepcao = Invoicyrecepcao
            Dim retVal As InvoiCyRecepcao.ExecuteResponse = CType(Me,InvoiCyRecepcao.recepcaoSoapPort).Execute(inValue)
            Return retVal.Invoicyretorno
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InvoiCyRecepcao_recepcaoSoapPort_ExecuteAsync(ByVal request As InvoiCyRecepcao.ExecuteRequest) As System.Threading.Tasks.Task(Of InvoiCyRecepcao.ExecuteResponse) Implements InvoiCyRecepcao.recepcaoSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
        
        Public Function ExecuteAsync(ByVal Invoicyrecepcao As InvoiCyRecepcao.InvoiCy) As System.Threading.Tasks.Task(Of InvoiCyRecepcao.ExecuteResponse)
            Dim inValue As InvoiCyRecepcao.ExecuteRequest = New InvoiCyRecepcao.ExecuteRequest()
            inValue.Invoicyrecepcao = Invoicyrecepcao
            Return CType(Me,InvoiCyRecepcao.recepcaoSoapPort).ExecuteAsync(inValue)
        End Function
    End Class
End Namespace
